[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install --prefix dashboard"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build --prefix dashboard"]

[start]
cmd = "npm start --prefix dashboard"
