[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.build]
dependsOn = ["setup"]
cmds = [
  "npm install --prefix dashboard",
  "npm run build --prefix dashboard"
]

[start]
cmd = "npm start --prefix dashboard"
